apiVersion: v1
kind: Service
metadata:
  labels:
    app: gar-proxy
  name: gar-proxy-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: gar
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gar-proxy-ingress
spec:
  backend:
    serviceName: gar-proxy-service
    servicePort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gar-proxy-hpa
  namespace: default
spec:
  scaleTargetRef: # ここでautoscale対象となる`scaled resource object`を指定
    apiVersion: apps/v1
    kind: Deployment
    name: gar-proxy
  minReplicas: 1 # 最小レプリカ数
  maxReplicas: 10 # 最大レプリカ数
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70 # CPU使用率が常に70%になるように指定